server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  application:
    name: dscommerce
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  jpa:
    hibernate:
      format_sql: true
      open-in-viwer: true
    show-sql: true